# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install system dependencies for ffmpeg and pillow build
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
       ffmpeg \
       build-essential \
       libjpeg-dev \
       zlib1g-dev \
       libtiff-dev \
       libopenjp2-7-dev \
       libfreetype6-dev && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Default command for stdio MCP server
CMD ["python", "server.py"]
